name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get release version
        id: get_version
        run: echo ::set-env name=GIT_REVISION::$(echo ${GITHUB_SHA})
      - name: Get the tag
        id: get_tag
        run: echo ::set-env name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
      - name: Publish image to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.15
        with:
          name: ignition-manifests-and-kubeconfig-generate
          username: ${{ secrets.OCPMETAL_USERNAME }}
          password: ${{ secrets.OCPMETAL_PASSWORD }}
          REGISTRY: 'quay.io/ocpmetal'
          dockerfile: Dockerfile.baremetal
          buildargs: GIT_REVISION
          tags: "${{ env.GIT_TAG }},${{ env.GIT_REVISION }}"
